# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :mac do
  desc "Run Mac OS tests"
  lane :macos_tests do
    run_tests(
      project: "EssentialFeed.xcodeproj",
      scheme: "CI_macOS",
      clean: false
    )
  end
end

platform :ios do
  desc "Run iOS tests"
  lane :ios_tests do
    run_tests(
      project: "EssentialFeed.xcodeproj",
      scheme: "CI_iOS",
      clean: false
    )
  end
end

desc "Run all CI tests"
lane :all_tests do
  sh "fastlane mac macos_tests"
  sh "fastlane ios ios_tests"
end
